version: '3.8'

services:
  odin:
    container_name: odin
    image: aichenskyi/odin:latest
    ports:
      - "1234:1234"
    depends_on:
      - bor
  bor:
    container_name: bor
    image: aichenskyi/bor:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - HNSWLIB_NO_NATIVE=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - MOCK="False"
    volumes:
      - chroma_data:/etc/chroma
    depends_on:
      - memgraph
  memgraph:
    image: memgraph/memgraph-mage:1.15-memgraph-2.15
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - mg_lib:/var/lib/memgraph

volumes:
  chroma_data:
  mg_lib:
